---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - ntp
    - ntpstat
    - tzdata

- name: Configure ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - Restart NTP service

- name: Enable and start NTP service
  systemd:
    name: ntp
    enabled: yes
    state: started

- name: Validate if systemd's cron.service exists
  stat:
    path: /lib/systemd/system/cron.service
  register: cron_service
  changed_when: False
  check_mode: False

- name: Validate cron.service status
  command: systemctl status cron.service
  when: cron_service.stat.exists
  register: cron_daemon
  failed_when:  cron_daemon.rc == 2
  changed_when: False
  check_mode: False

- name: Configure Timezone
  timezone:
    name: "{{ ntp_timezone }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: Restart Cron service if exists