# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = 2

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define 'xenial' do |ubuntu|
    ubuntu.vm.box = 'everproven/ubuntu-1604'
  end
end
